name: Build & Create Downloadable Artifact
on:
  workflow_dispatch:
    inputs:
      version:
        description: '手动指定插件版本号，例如: 1.0.0'
        required: true
        default: '1.0.0'

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      DALAMUD_HOME: /tmp/dalamud

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Version Tag
        run: echo "tag=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Download Dalamud Latest
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -O ${{ env.DALAMUD_HOME }}.zip
          unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Restore Project
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release vnavmesh/vnavmesh.csproj -p:AssemblyVersion=${{ env.tag }}

      - name: Upload Plugin Artifact ✨
        uses: actions/upload-artifact@v4
        with:
          name: vnavmesh-plugin-${{ env.tag }}
          path: vnavmesh/bin/Release/
